### FILME

### Listar

GET https://localhost:5001/api/filmes/listar

### Cadastrar

POST https://localhost:5001/api/filmes/cadastrar
Content-Type: application/json

{
    "Nome" : "Harry Potter",
    "Ano" : "2002",
    "GeneroId" : 1
}
###

### Buscar

### Buscar por nome

GET https://localhost:5001/api/filmes/buscarpornome/Harry Potter

### Buscar por ano

GET https://localhost:5001/api/filmes/buscarporano/2001

### Editar

PUT  https://localhost:5001/api/filmes/editar
Content-Type: application/json

{
    "filmeId" : 8,
    "Nome" : "FUnciona?",
    "Ano" : "2022",
    "GeneroId" : 1
}

### Deletar

DELETE https://localhost:5001/api/filmes/deletar/1
