### Atores

### Listar

GET https://localhost:5001/api/atores/listar

### Cadastrar

POST https://localhost:5001/api/atores/cadastrar
Content-Type: application/json

{
    "Nome" : "Alfredo Go",
    "Nascimento" : "1962-06-03",
    "FilmeId" : 1
}