### Atores

### Listar

GET https://localhost:5001/api/atores/listar

### Cadastrar


POST https://localhost:5001/api/atores/cadastrar
Content-Type: application/json

{
    "Nome" : "Dennis Quaid",
    "Nascimento" : "1954-04-09"
}