### FILME

### Listar

GET https://localhost:5001/api/filmes/listar

### Cadastrar

POST https://localhost:5001/api/filmes/cadastrar
Content-Type: application/json

{
    "Nome" : "testando",
    "Ano" : "2021",
    "GeneroId" : 1
}

###
POST https://localhost:5001/api/filmes/cadastrar
Content-Type: application/json

{
    "Nome" : "testando 2",
    "Ano" : "2022",
    "GeneroId" : 2
}

### Buscar

### Buscar por nome

GET https://localhost:5001/api/filmes/buscarpornome/testando 2

### Buscar por genero

GET https://localhost:5001/api/filmes/buscarporgenero/2

### Buscar por ano

GET https://localhost:5001/api/filmes/buscarporano/2021
