### FILME

### Listar

GET https://localhost:5001/api/filmes/listar

### Cadastrar

POST https://localhost:5001/api/filmes/cadastrar
Content-Type: application/json

{
    "Nome" : "Missão Impossível",
    "Ano" : "1996",
    "GeneroId" : 1
}