### GENERO

### Listar

GET https://localhost:5001/api/generos/listar

### Cadastrar - Ex: Terror / Comedia / Ação / Aventura / Musical / Documentario

POST https://localhost:5001/api/generos/cadastrar
Content-Type: application/json

{
    "Nome" : "Acao"
}

###

POST https://localhost:5001/api/generos/cadastrar
Content-Type: application/json

{
    "Nome" : "Ficçao Cientifica"
}

### Editar

PUT https://localhost:5001/api/generos/editar
Content-Type: application/json

{
    "Nome" : "Terror"
}

### Deletar
DELETE https://localhost:5001/api/Atores/deletar/3
